---
title: "leaflet-GIS"
author: "Stanley Mastrantonis"
date: '2022-06-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(leaflet)
library(mapview)
library(mapedit)
library(leafpm)
library(shiny)
library(tidyverse)

```

```{r leaflet draw, include = FALSE}
i <<- 1
i_edit <<- 1
feat_list  <<- list()
edit_list <<- list()

ui = fluidPage(
  tabsetPanel(
    tabPanel("Map",
             leafletOutput("mymap"),
             textInput("label", "Label", "Smith_Pad_1_Soil")
    ),
    tabPanel("Debug",
             verbatimTextOutput("debug_out")
    )
  )
  
)


server <- function(input, output, session){
  output$debug_out <- renderPrint(reactiveValuesToList(input))
  
  output$mymap <- renderLeaflet(
    leaflet() %>%
      addProviderTiles("Esri.WorldImagery") %>%
      setView(lng = -166, lat = 58.0, zoom = 5) %>%
      addPmToolbar(targetGroup = 'draw',
        toolbarOptions = pmToolbarOptions(drawMarker = FALSE, 
                                          drawPolyline = FALSE,
                                          cutPolygon = TRUE,
                                          position = "topright"),
        drawOptions = pmDrawOptions(snappable = FALSE, allowSelfIntersection = FALSE),
        editOptions = pmEditOptions(preventMarkerRemoval = TRUE, draggable = TRUE),
        cutOptions = pmCutOptions(snappable = FALSE, allowSelfIntersection = FALSE)
      )
  )
  
  
  observeEvent(input$mymap_draw_new_feature,{
    #print(input)
    feature <<- input$mymap_draw_new_feature
    feat_list[[i]] <<- geojsonsf::geojson_sf(jsonify::to_json(feature, unbox = T))
    i <<- i+1
  })
  
  observeEvent(input$mymap_draw_edited_features, {
    cutfeature <<- input$mymap_draw_edited_features
    edit_list[[i]] <<- geojsonsf::geojson_sf(jsonify::to_json(cutfeature, unbox = T))
    i_edit <<- i_edit+1
    #print(cutfeature)
    
  })
  

  
}

shinyApp(ui = ui, server = server)


```


```{r bind}

result = do.call(rbind, lapply(feat_list, st_sf))

map_aoi_create = leaflet() %>% 
                 addTiles() %>% 
                 addPolygons(data = result) %>%
                 #addMouseCoordinates() %>%
                 addScaleBar()  
  
map_aoi_create



```




if (length(feat_list) == 1){
    featpol = feat_list[[1]]
    
      } else {
        
        endpol = feat_list[[1]]
        
    for (n in 2:length(feat_list)) {
      featpol = c(endpol, feat_list[[n]])
    }
        
  }


if (!exists('edit_list')){
        
        edit_list = NULL
        rm('edit_list')
        
      } else {
        if (length(edit_list) == 1) {
         editpol = edit_list[[1]]
         
            } else {
              
              editpol = edit_list[[1]]
              for (n in 2:length(edit_list)) {
                editpol = c(editpol, edit_list[[n]])
           }
      }    
}


```






